### ISSUE TITLE
Errors are swallowed during dev

### ISSUE THREAD

**Issue by zephraph** [artsy/express-reloadable#10]
There was a syntax error from babel while running metaphysics dev that was being swallowed by this lib. 

cc @alloy

**Comment by damassi** [comment]
@zephraph - any more context / info / error being swallowed, etc?

**Comment by zephraph** [comment]
I'll follow back up tomorrow. Just wanted a place holder so I wouldn't forget. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zephraph** [comment]
Bleh, I can't find my notes on this. If they show up I'll open the issue back up.
