### ISSUE TITLE
Add ability to pass in array of watched paths

### ISSUE THREAD

**Issue by damassi** [artsy/express-reloadable#2]
e.g., 
```javascript
const reloadAndMount = createReloadable(app, require)
reloadAndMount(['foo', 'bar', 'baz'])
```

**Comment by alloy** [comment]
Is there any reason to do this _other_ than the situation you were having with `node_modules`? My general opinion is that ‘configuration’ is an anti-pattern.

Naively I would think that the problem is that FSEvents and similar kernel features (I assume chokidar supports e.g. kqueue on other platforms) don’t follow symlinks, in which case the solution would be to automatically add watch paths for each entry in `node_modules/` that is a symlink to its original location. Have you experimented with that?

**Comment by damassi** [comment]
@alloy - I like the idea of detecting symlinks and then auto-configuring, but I think that this is outside of the scope of this module. Somewhat related to my response to @craigspaeth as to why we don't just watch the entire `node_modules` directory, making assumptions about that folder would be unwise, IMO, for performance and stability reasons. For example, many tools and processes use symlinks (like lerna, and yarn's new `workspaces` feature, amongst many other build tools, etc) and I don't think it's `express-reloadable`'s job to maintain safe connections inside of there or to be aware of connections that may or may not have to do with immediate DX-specific source-code changes. 

I share your opinion about minimal configuration (less is more, in many cases), but in this instance where there are hard listeners being established between trees of folders and files that can oftentimes consume a lot of memory, I think keeping things bounded via opt-in is preferable. `watchModules`, one of two config options,` does what it says: "watch these node modules and reload on change". The fact that we're naively modifying `require` caches also reenforces this in my mind.

I'm totally open to refactoring this at a later point in time but I think the current "no surprises / minimal weirdness" approach is best for our (and most everyone else's) use-cases.

**Comment by alloy** [comment]
I disagree that it is beyond the scope of this module. This module is about making DX while working on a server better, so why not make all the conceptually same situations work? That is, working on files that are part of the app (that includes the default load path) and expecting your node server to reload files ASAP.

All those dev tools you mention work afaik the same way, namely they symlink into the default load path, so it’s not really likely to ever need configuration. Whereas with manual configuration the dev suddenly needs to understand this dev dependency, or even know it exists, at a time that they are unlikely to be interested in dealing with those details.

Performance is a different topic altogether. If for some reason this takes up a bunch of memory and/or is slow, that sounds like another thing we could fix. FSEvents is a kernel feature that’s meant to work with huge trees, even a FS root should be fine. Can you elaborate on this resource hungry behavior?

**Comment by damassi** [comment]
While googling trying to figure out how to articulate past situations I've run into, I [saw this](https://www.npmjs.com/package/graceful-chokidar)
> Watching files in node.js is a total nightmare. Chokidar makes the whole experience much less painful, but it's not foolproof - I've often encountered EMFILE (too many open files) errors when using it to watch large directories.

> This fork simply replaces require('fs') with require('graceful-fs'). graceful-fs is a drop-in replacement for the native fs that prevents EMFILE errors from occurring. It also removes the optional dependency on fsevents (the native filesystem events binding), because I've experienced segmentation faults while using it.

I've run into this situation a few times before, and while I doubt individual library code will contain enough files to crash the process, in aggregate this could very well be the case. I can imagine situations where _all_ `node_modules` are symlinks (for example in networked environments); I can also imagine each of those networked symlinks symlinking internally to other networked paths. 

Basically, this is a bounds issue. Right now the package, by design, says 

```
const mountAndReload = createReloadable(app, require)
mountAndReload('./client')
```

"Watch a single folder, represented by a mountable express app, for changes." It doesn't say "watch this folder as well as all found symlinks -- however many or few -- from your app's `node_modules` directory". By introducing that piece of functionality we're exponentially increasing the surface area for failure and / or conflict as well as exposing content typically considered a black box. 

I'm down with experimenting with `graceful-chokidar` to reduce potential issues, but I'm just not convinced yet that this requirement should be contained in `express-reloadable`. Where I _could_ see it making sense is in another (separate) module specifically related to linked-module development.

**Comment by alloy** [comment]
Ooph, that sounds bad!

FSEvents itself shouldn’t afaik be opening any files, so the `EMFILE` can only be caused by something else? I’d love to know more details when/if you run into it again or know of tickets with more details. In any case, the [fsevents](https://github.com/strongloop/fsevents) package seems well maintained and a segfault should _never_ occur in a node app, so I kinda feel like that shouldn’t technically prohibit us and we could expect it to work as expected.

The depth of trees and the amount of files therein do not influence the performance of the native (underlying) FSEvents API, it’s the code that does something with the received events that can have such an impact.

Regarding networked environments, can you shed more light on what such a app dev situation could be?

**Comment by damassi** [comment]
> I can imagine situations where all node_modules are symlinks (for example in networked environments)

I'm thinking weird corporate environments, Vagrant, Docker, etc. Further specifics I don't have; this is mostly a hunch for safety reasons. 

Applications can be complex, and tooling to support said applications even more-so. Symlinks + Node have been problematic in the past, as has been watching large amounts of files. A great deal of iteration also occurs in `chokdar`, which is multiplied by the number of folders being watched.  If you're certain that this is safe in all environments (which you seem to be, Windows included 😄), while also certain that exposing potentially unbounded `node_module` symlink trees within the context of this express-subroute-specific library is a good idea I'd be happy to open a PR after other work is complete in which to explore. For the record, however, I very much think we should keep this simple, dumb, easy and bounded. `watchModules` is like `watchFiles[]`, `include[]`, `exclude[]` and all of the other common settings-patterns that have been laid down around file-system observance through the years in projects like `nodemon`, `forever`, `grunt`, `gulp`, `webpack`, and so on. 

Totally down to experiment tho!
