### ISSUE TITLE
Please put option: recursive into README.MD

### ISSUE THREAD

**Issue by Cow258** [artsy/express-reloadable#41]
I think the option `recursive` should default `true`,
and force to use `decache` all the time,
that prevent memory leak.

Also if here are `recursive` option in the code,
so you should put it into `README.MD`.

Thank you.

**Comment by Cow258** [comment]
but using `decache` will lose some initialized object

**Comment by damassi** [comment]
HI @Cow258 - we've been using this lib in its current form (without `recursive` or `decache`) for years now without issues. The setting is there for folks who dig and need more control, but not by default.
