### ISSUE TITLE
Stacktraces are obfuscated for fatal crashes

### ISSUE THREAD

**Issue by l2succes** [artsy/express-reloadable#6]
After making a change to our express config, I realized the server was crashing with a weird internal v8 error. Then it occurred to me that `express-reloadable` needed to bust an internal node module cache to work. Here's the code in question. 

Before:
```javascript
// Enable server-side code hot-swapping on change
const mountAndReload = createReloadable(app, require)

app.use('/api', mountAndReload('./api', {
  mountPoint: '/api'
}))

mountAndReload('./client', {
  watchModules: [
    '@artsy/reaction-force'
  ]
})
```

<img width="1145" alt="screen shot 2018-01-23 at 11 36 40 am" src="https://user-images.githubusercontent.com/296775/35340039-21aaeafa-00f0-11e8-810e-6ddabd762a2d.png">

After:
```javascript
app.use('/api', require('./api'))
app.use(require('./client'))
```

<img width="850" alt="screen shot 2018-01-23 at 2 27 23 pm" src="https://user-images.githubusercontent.com/296775/35340036-20b20f7a-00f0-11e8-91e0-0c61c4838031.png">

after replacing the `mountAndReload` calls with the standard express `app.use`, the stacktrace was actually showing the line in javascript that was crashing the server.

**Comment by damassi** [comment]
Looking around, will investigate a less naive implementation, e.g., https://stackoverflow.com/questions/9210542/node-js-require-cache-possible-to-invalidate/14801711#14801711
